diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager-core
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\Emilio\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
user.name=emilioBrizuela
user.email=emilio_brizuela@hotmail.com
filesystem.Oracle Corporation|1.8.0_271|305145718.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_271|305145718.minracythreshold=0 nanoseconds
filesystem.Oracle Corporation|11.0.10|305145718.timestampresolution=999 microseconds
filesystem.Oracle Corporation|11.0.10|305145718.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/luiscursomean2021/appcitas.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=test-emi
branch.main.merge=refs/heads/main
remote.test-emi.url=https://github.com/luiscursomean2021/appcitas.git
remote.test-emi.fetch=+refs/heads/*:refs/remotes/test-emi/*
